# Generated by Django 3.1 on 2023-07-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230720_1106'),
        ('cart', '0003_auto_20230716_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='varations',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
