# Generated by Django 3.1 on 2023-07-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_varations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='varations',
            new_name='variations',
        ),
    ]
